#!/bin/bash

Z="$(printf '\033[0m')"
r="$(printf '\033[0;31m')"
R="$(printf '\033[1;31m')"
g="$(printf '\033[0;32m')"
G="$(printf '\033[1;32m')"
y="$(printf '\033[0;33m')"
Y="$(printf '\033[1;33m')"
W="$(printf '\033[1;37m')"
c="$(printf '\033[0;36m')"
C="$(printf '\033[1;36m')"

clear

for pkg in x11-repo tigervnc florence ; do
        echo -e "
${R} [${W}-${R}]${G} Installing package : ${Y}$pkg${Z}
"
	pkg install $pkg -y
done

echo -e "
 ${Y}Enter Your Password & Confirmed it Once then type ${R}n${Z}
"

vncserver -listen tcp

vncserver -list

killall Xvnc

killall Xvnc

killall Xvnc

cp -rf vnc /data/data/com.termux/files/usr/bin/vnc
cp -rf launchVNC /data/data/com.termux/files/usr/bin/launchVNC

echo "#!/bin/bash
/data/data/com.termux/files/usr/bin/vnc" > /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/usr/local/bin/vnc

echo "#!/bin/bash
termux-open vnc://localhost:1" > /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/usr/local/bin/launchVNC

echo -e "
 ${c}vnc ${y}copied to ${c}/usr/bin/vnc
"

chmod +x /data/data/com.termux/files/usr/bin/*
chmod +x /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/usr/local/bin/*

echo -e "
 ${g}Executable ${r}Permission ${y}is set to ${c}vnc
"

bash progress 2
sleep 1

termux-open https://play.google.com/store/apps/details?id=com.realvnc.viewer.android

echo -e "
 ${c}VNC Server ${y}Installed.

 Use ${C}vnc ${g}command to run ${y}VNC Server.${Z}

"
