#!/bin/bash

C=$1

function ProgressBar {

	let _progress=(${1}*100/${2}*100)/100
	let _done=(${_progress}*4)/10
	let _left=40-$_done

	_fill=$(printf "%${_done}s")
	_empty=$(printf "%${_left}s")

	printf "\r\033[0;3${C}m ${_fill// /▇}${_empty// /' '}\033[1;33m ${_progress}%%"

}

_start=0

_end=50

for number in $(seq ${_start} ${_end}); do
	sleep 0.001
	ProgressBar ${number} ${_end}
done

echo ""
