#!/bin/bash

Z="$(printf '\033[0m')"
R="$(printf '\033[1;31m')"
g="$(printf '\033[0;32m')"
G="$(printf '\033[1;32m')"                                                                                                                               Y="$(printf '\033[1;33m')"
W="$(printf '\033[1;37m')"                                                                                                                               C="$(printf '\033[1;36m')"

packs=(tigervnc-standalone-server tigervnc-common)
for pack in "${packs[@]}"; do
        type -p "$pack" &>/dev/null || {
                echo -e "
${R} [${W}-${R}]${R} Un-Installing package : ${Y}$pack
"${Z}
                sudo apt remove --purge $pack -y
		sudo apt autoclean
		sudo apt autoremove --purge
        }
done

echo ""

rm -rf /usr/local/bin/vnc

bash progress 1

echo -e "
 ${R}Un-Installed.${Z}
"
