#!/bin/bash

Z="$(printf '\033[0m')"
R="$(printf '\033[1;31m')"
g="$(printf '\033[0;32m')"
G="$(printf '\033[1;32m')"
Y="$(printf '\033[1;33m')"
W="$(printf '\033[1;37m')"
C="$(printf '\033[1;36m')"

START=0
STOP=1
DIALOG_ESC=255
HEIGHT=0
WIDTH=0

export PULSE_SERVER=127.0.0.1
export MOZ_FAKE_NO_SANDBOX=1

stop() {
	printf "${R}"

	tigervncserver -kill :*
	rm -rf /username/.vnc/localhost:*.pid
	rm -rf /tmp/.X1-lock
	rm -rf /tmp/.X11-unix/X1

	printf "${Z}"
}

start() {
	printf "${g}"

	tigervncserver \
		-xstartup /usr/bin/startxfce4 \
		-geometry 1512x750 \
		-localhost no :1 \
		-pixelformat rgb888 \
		-depth 32 \
		-SecurityTypes None \
		--I-KNOW-THIS-IS-INSECURE

	$PREFIX/bin/termux-open vnc://localhost:5901

	printf "${Z}"
}

while true; do
	dialog \
		--title "VNC" \
		--clear \
		--yes-label "Start" \
		--no-label "Stop" \
	--yesno "" $HEIGHT $WIDTH

	case $? in
		$START )
			clear

			stop
			start

		break
		;;
		$STOP )
			clear

			stop
		break
		;;
		$DIALOG_ESC )
			clear
			exit 1
		break
		;;
	esac
done
