#!/bin/bash

Z="$(printf '\033[0m')"
R="$(printf '\033[1;31m')"
g="$(printf '\033[0;32m')"
G="$(printf '\033[1;32m')"
Y="$(printf '\033[1;33m')"
W="$(printf '\033[1;37m')"
C="$(printf '\033[1;36m')"

PORTRAIT=0
LANDSCAPE=1
DIALOG_ESC=255
HEIGHT=0
WIDTH=0

export PULSE_SERVER=127.0.0.1
export MOZ_FAKE_NO_SANDBOX=1

stop() {
        printf "${R}"

        killall Xvnc
        rm -rf /data/data/com.termux/files/usr/tmp/.X*

        printf "${Z}"
}

start() {
        printf "${g}"

        vncserver -listen tcp -geometry $1 -SecurityTypes None

        printf "${Y}"

        vncserver -list

        termux-open vnc://localhost:5901

        printf "${Z}"
}

while true; do
        dialog \
                --title "VNC" \
                --clear \
                --yes-label "Portrait" \
                --no-label "Landscape" \
                --yesno "" $HEIGHT $WIDTH

        case $? in
                $PORTRAIT )
                        clear

                        stop
                        start 972x1210

                break
                ;;
                $LANDSCAPE )
                        clear

                        stop
                        start 1512x750
                break
                ;;
                $DIALOG_ESC )
                        clear
                        exit 1
                break
                ;;
        esac
done
